version: "2"


services:
  mongodb-dev-primary:
    image: "bitnami/mongodb:latest"
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/bitnami
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_USERNAME=
      - MONGODB_PASSWORD=
      - MONGODB_DATABASE=security_01
#      - MONGODB_REPLICA_SET_MODE=primary
#      - MONGODB_ROOT_PASSWORD=rootpass1
#      - MONGODB_REPLICA_SET_KEY=replicasetkey123
#      - MONGODB_REPLICA_SET_NAME=rs1